export const TABLE_DATA = [
  {
    id: 1,
    group: "E",
    category: "Air pollution",
    indicator: "CO2 emissions",
    scope: 1,
    dimension: "Current state",
    type: "Key",
    unit: "kt",
  },
  {
    id: 2,
    group: "E",
    category: "Air pollution",
    indicator: "CO2 emissions (change in last 3 years)",
    scope: 1,
    dimension: "Ability & willingness",
    type: "Key",
    unit: "CAGR, %",
  },
  {
    id: 3,
    group: "E",
    category: "Air pollution",
    indicator: "CO2 concentration",
    scope: 1,
    dimension: "Current state",
    type: "Key",
    unit: "ppm",
  },
  {
    id: 4,
    group: "E",
    category: "Air pollution",
    indicator: "CO2 concentration (change in last 3 years)",
    scope: 1,
    dimension: "Ability & willingness",
    type: "Key",
    unit: "CAGR, %",
  },
  {
    id: 5,
    group: "E",
    category: "Air pollution",
    indicator: "Annual average of SO2 concentration in ambient air",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "microgram/m3",
  },
  {
    id: 6,
    group: "E",
    category: "Air pollution",
    indicator:
      "Annual Average of SO2 Concentration in Ambient Air (change in last 3 years)",
    scope: 0,
    dimension: "Ability & willingness",
    type: "Key",
    unit: "CAGR, %",
  },
  {
    id: 7,
    group: "E",
    category: "Air pollution",
    indicator: "Annual Average of NO2 Concentration in Ambient Air",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "microgram/m3",
  },
  {
    id: 8,
    group: "E",
    category: "Air pollution",
    indicator:
      "Annual Average of NO2 Concentration in Ambient Air (change in last 3 years)",
    scope: 0,
    dimension: "Ability & willingness",
    type: "Key",
    unit: "CAGR, %",
  },
  {
    id: 9,
    group: "E",
    category: "Air pollution",
    indicator: "Annual Average of O3 Concentration in Ambient Air",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "microgram/m3",
  },
  {
    id: 10,
    group: "E",
    category: "Air pollution",
    indicator:
      "Annual Average of O3 Concentration in Ambient Air (change in last 3 years)",
    scope: 0,
    dimension: "Ability & willingness",
    type: "Key",
    unit: "CAGR, %",
  },
  {
    id: 11,
    group: "E",
    category: "Air pollution",
    indicator: "Annual Average of CO Concentration in Ambient Air",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "microgram/m3",
  },
  {
    id: 12,
    group: "E",
    category: "Air pollution",
    indicator:
      "Annual Average of CO Concentration in Ambient Air (change in last 3 years)",
    scope: 0,
    dimension: "Ability & willingness",
    type: "Key",
    unit: "CAGR, %",
  },
  {
    id: 13,
    group: "E",
    category: "Air pollution",
    indicator:
      "Annual Average of Particulate Matter (PM10) Concentration in Ambient Air",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "microgram/m3",
  },
  {
    id: 14,
    group: "E",
    category: "Air pollution",
    indicator:
      "Annual Average of Particulate Matter (PM10) Concentration in Ambient Air (change in last 3 years)",
    scope: 0,
    dimension: "Ability & willingness",
    type: "Key",
    unit: "CAGR, %",
  },
  {
    id: 15,
    group: "E",
    category: "Air pollution",
    indicator: "Volatile organic compounds/reactive organic gases emissions",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "microgram/m3",
  },
  {
    id: 16,
    group: "E",
    category: "Air pollution",
    indicator: "Perception of air pollution index",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "index",
  },
  {
    id: 17,
    group: "E",
    category: "Air pollution",
    indicator: "Paris Agreement",
    scope: 3,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "Yes/No",
  },
  {
    id: 18,
    group: "E",
    category: "Water pollution",
    indicator: "Annual average of dissolved oxygen (DO) concentration in water",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 19,
    group: "E",
    category: "Water pollution",
    indicator: "Annual average of pH concentration in water",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "pH",
  },
  {
    id: 20,
    group: "E",
    category: "Water pollution",
    indicator: "Annual average dissolved solids in drinking water",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "ppm",
  },
  {
    id: 21,
    group: "E",
    category: "Water pollution",
    indicator: "Water management strategy in a city",
    scope: 1,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "Yes/No",
  },
  {
    id: 22,
    group: "E",
    category: "Water pollution",
    indicator: "Perception of water pollution index",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "index",
  },
  {
    id: 23,
    group: "E",
    category: "Land use and waste",
    indicator:
      "Share of devastated and degraded land area requiring reclamation",
    scope: 1,
    dimension: "Current state",
    type: "Key",
    unit: "%",
  },
  {
    id: 24,
    group: "E",
    category: "Land use and waste",
    indicator:
      "3-year average growth rate of devastated and degraded land area requiring reclamation",
    scope: 1,
    dimension: "Ability & willingness",
    type: "Key",
    unit: "CAGR, %",
  },
  {
    id: 25,
    group: "E",
    category: "Land use and waste",
    indicator: "Waste deposits",
    scope: 0,
    dimension: "Current state",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 26,
    group: "E",
    category: "Land use and waste",
    indicator:
      "Collected and managed in dumps wastes (hazardous and non-hazardous)",
    scope: 0,
    dimension: "Current state",
    type: "Supportive",
    unit: "kg per capita ",
  },
  {
    id: 27,
    group: "E",
    category: "Land use and waste",
    indicator:
      "Collected and managed in dumps wastes (hazardous and non-hazardous), (change in last 3 years)",
    scope: 0,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "CAGR, %",
  },
  {
    id: 28,
    group: "E",
    category: "Land use and waste",
    indicator: "Total recycled construction waste",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "tons per capita",
  },
  {
    id: 29,
    group: "E",
    category: "Land use and waste",
    indicator:
      "Share of recycled construction and demolish waste in total generated construction and demolish waste",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 30,
    group: "E",
    category: "Land use and waste",
    indicator:
      "Total area of impervious surfaces and percentage to total city area",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 31,
    group: "E",
    category: "Land use and waste",
    indicator: "Productive urban land, % of total area",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 32,
    group: "E",
    category: "Land use and waste",
    indicator: "Waste management strategy",
    scope: 1,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "Yes/No",
  },
  {
    id: 33,
    group: "E",
    category: "Land use and waste",
    indicator: "Perception of waste index",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "index",
  },
  {
    id: 34,
    group: "E",
    category: "Land use and waste",
    indicator: "Green spaces, % city area",
    scope: 1,
    dimension: "Current state",
    type: "Key",
    unit: "%",
  },
  {
    id: 35,
    group: "E",
    category: "Land use and waste",
    indicator: "Green spaces, change in last 3 years",
    scope: 1,
    dimension: "Ability & willingness",
    type: "Key",
    unit: "CAGR, %",
  },
  {
    id: 36,
    group: "E",
    category: "Land use and waste",
    indicator: "NDVI (Normalized Difference Vegetation Index)",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "index",
  },
  {
    id: 37,
    group: "E",
    category: "Natural disaster hazards",
    indicator:
      "Share of total area with altitude above sea level less than 0,5 meters",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 38,
    group: "E",
    category: "Natural disaster hazards",
    indicator: "Growth rate of freshwater mirror area",
    scope: 1,
    dimension: "Ability & willingness",
    type: "Key",
    unit: "%",
  },
  {
    id: 39,
    group: "E",
    category: "Natural disaster hazards",
    indicator:
      "Number of registered heavy rain, flood and thunderbolt (change in last 3 years)",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "CAGR, %",
  },
  {
    id: 40,
    group: "E",
    category: "Natural disaster hazards",
    indicator: "Number of registered sandstorm (change in last 3 years)",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "CAGR, %",
  },
  {
    id: 41,
    group: "E",
    category: "Natural disaster hazards",
    indicator: "Environmental/natural disasters’ risk mitigation",
    scope: 1,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "Yes/No",
  },
  {
    id: 42,
    group: "E",
    category: "Natural disaster hazards",
    indicator:
      "Strategy/policy/government officials’ statement on environmental issues ",
    scope: 1,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "Yes/No",
  },
  {
    id: 43,
    group: "E",
    category: "Natural disaster hazards",
    indicator: "Total overall losses from natural disaster hazards",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "US$ mln ",
  },
  {
    id: 44,
    group: "E",
    category: "Natural disaster hazards",
    indicator:
      "Number of days with average daily temperature above the threshold for 1990-2010",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "days",
  },
  {
    id: 45,
    group: "E",
    category: "Natural disaster hazards",
    indicator:
      "Number of disruptions to basic services, attributed to disasters",
    scope: 0,
    dimension: "Current state",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 46,
    group: "S",
    category: "Water availability",
    indicator: "Water consumption per capita",
    scope: 0,
    dimension: "Current state",
    type: "Supportive",
    unit: "mcm per capita",
  },
  {
    id: 47,
    group: "S",
    category: "Water availability",
    indicator: "Water tariff to disposable income ratio",
    scope: 0,
    dimension: "Current state",
    type: "Supportive",
    unit: "ratio",
  },
  {
    id: 48,
    group: "S",
    category: "Water availability",
    indicator: "Sanitary facilities tariff to disposable income ratio",
    scope: 0,
    dimension: "Current state",
    type: "Supportive",
    unit: "ratio",
  },
  {
    id: 49,
    group: "S",
    category: "Water availability",
    indicator: "Water consumption per capita (change in last 3 years)",
    scope: 1,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "CAGR, %",
  },
  {
    id: 50,
    group: "S",
    category: "Water availability",
    indicator: "Percentage of population with access to drinking water",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "%",
  },
  {
    id: 51,
    group: "S",
    category: "Water availability",
    indicator:
      "Percentage of population with access to drinking water (change in last 3 years)",
    scope: 0,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "CAGR, %",
  },
  {
    id: 52,
    group: "S",
    category: "Water availability",
    indicator: "Percentage of population with access to sanitary facilities",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "%",
  },
  {
    id: 53,
    group: "S",
    category: "Water availability",
    indicator:
      "Percentage of population with access to sanitary facilities (change in last 3 years)",
    scope: 0,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "CAGR, %",
  },
  {
    id: 54,
    group: "S",
    category: "Food availability",
    indicator: "Cereal import dependency ratio (5-years average)",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "ratio",
  },
  {
    id: 55,
    group: "S",
    category: "Food availability",
    indicator: "Cereal import dependency ratio (change in last 3 years)",
    scope: 1,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "CAGR, %",
  },
  {
    id: 56,
    group: "S",
    category: "Food availability",
    indicator: "Prevalence of undernourishment",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "%",
  },
  {
    id: 57,
    group: "S",
    category: "Food availability",
    indicator: "Prevalence of undernourishment (change in last 3 years)",
    scope: 0,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "CAGR, %",
  },
  {
    id: 58,
    group: "S",
    category: "Food availability",
    indicator: "Prevalence of undernourishment children",
    scope: 0,
    dimension: "Current state",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 59,
    group: "S",
    category: "Food availability",
    indicator:
      "Prevalence of undernourishment children (change in last 3 years)",
    scope: 0,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "CAGR, %",
  },
  {
    id: 60,
    group: "S",
    category: "Food availability",
    indicator:
      "Prevalence of moderate or severe food insecurity in the population",
    scope: 0,
    dimension: "Current state",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 61,
    group: "S",
    category: "Food availability",
    indicator: "Share of imports in food resources",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 62,
    group: "S",
    category: "Food availability",
    indicator:
      "Percentage of people with access to at least one food vendor/retailer within 15 minutes of walking",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 63,
    group: "S",
    category: "Food availability",
    indicator: "Perception of food availability index",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "index",
  },
  {
    id: 64,
    group: "S",
    category: "Energy availability",
    indicator: "Percentage of urban population with access to electricity",
    scope: 0,
    dimension: "Ability & willingness",
    type: "Key",
    unit: "%",
  },
  {
    id: 65,
    group: "S",
    category: "Energy availability",
    indicator:
      "Percentage of urban population with access to electricity (change in last 3 years)",
    scope: 0,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "CAGR, %",
  },
  {
    id: 66,
    group: "S",
    category: "Energy availability",
    indicator: "Consumption of electricity per capita",
    scope: 0,
    dimension: "Current state",
    type: "Supportive",
    unit: "kWh/person",
  },
  {
    id: 67,
    group: "S",
    category: "Energy availability",
    indicator: "Consumption of electricity per capita (change in last 3 years)",
    scope: 0,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "CAGR, %",
  },
  {
    id: 68,
    group: "S",
    category: "Energy availability",
    indicator: "Electricity tariff to disposable income ratio",
    scope: 0,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "ratio",
  },
  {
    id: 69,
    group: "S",
    category: "Energy availability",
    indicator: "Share of renewable sources in electricity consumption",
    scope: 2,
    dimension: "Current state",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 70,
    group: "S",
    category: "Energy availability",
    indicator: "Perception of energy availability index",
    scope: 0,
    dimension: "Current state",
    type: "Supportive",
    unit: "index",
  },
  {
    id: 71,
    group: "S",
    category: "Health",
    indicator: "Child mortality rate (under 5 years-old)",
    scope: 1,
    dimension: "Current state",
    type: "Key",
    unit: "% of live births ",
  },
  {
    id: 72,
    group: "S",
    category: "Health",
    indicator: "City ambulance",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "Yes/No",
  },
  {
    id: 73,
    group: "S",
    category: "Health",
    indicator: "Life expectancy at birth, years",
    scope: 1,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "years",
  },
  {
    id: 74,
    group: "S",
    category: "Health",
    indicator: "Life expectancy at birth goals",
    scope: 1,
    dimension: "Ability & willingness",
    type: "Key",
    unit: "index",
  },
  {
    id: 75,
    group: "S",
    category: "Health",
    indicator: "Number of hospital beds per 1,000 population",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "per 1,000",
  },
  {
    id: 76,
    group: "S",
    category: "Health",
    indicator: "Number of doctors per 1,000 population",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "per 1,000",
  },
  {
    id: 77,
    group: "S",
    category: "Health",
    indicator: "Maternal mortality ratio",
    scope: 0,
    dimension: "Current state",
    type: "Supportive",
    unit: "deaths per 1,000 live births",
  },
  {
    id: 78,
    group: "S",
    category: "Health",
    indicator: "Ambulance arrival speed",
    scope: 0,
    dimension: "Current state",
    type: "Supportive",
    unit: "min",
  },
  {
    id: 79,
    group: "S",
    category: "Education",
    indicator: "Literacy rate among population (15-24 Years)",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "%",
  },
  {
    id: 80,
    group: "S",
    category: "Education",
    indicator:
      "Literacy rate among population (15-24 Years) (change in last 3 years)",
    scope: 0,
    dimension: "Ability & willingness",
    type: "Key",
    unit: "CAGR, %",
  },
  {
    id: 81,
    group: "S",
    category: "Education",
    indicator: "Primary education engagement",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 82,
    group: "S",
    category: "Education",
    indicator: "Pupils per teacher rate",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "ratio",
  },
  {
    id: 83,
    group: "S",
    category: "Education",
    indicator:
      "Proportion of population with post-secondary and higher education",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 84,
    group: "S",
    category: "Wealth",
    indicator:
      "Percentage of population with food expenditure is above 52% of total expenditure",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "%",
  },
  {
    id: 85,
    group: "S",
    category: "Wealth",
    indicator: "Mean monthly salary",
    scope: 1,
    dimension: "Current state",
    type: "Key",
    unit: "US dollars thousand PPP",
  },
  {
    id: 86,
    group: "S",
    category: "Wealth",
    indicator: "Mean monthly salary, change in last 3 years",
    scope: 1,
    dimension: "Ability & willingness",
    type: "Key",
    unit: "CAGR, %",
  },
  {
    id: 87,
    group: "S",
    category: "Wealth",
    indicator: "Disposable monthly income",
    scope: 0,
    dimension: "Current state",
    type: "Supportive",
    unit: "US dollars thousand PPP",
  },
  {
    id: 88,
    group: "S",
    category: "Wealth",
    indicator: "Disposable monthly income (change in last 3 years)",
    scope: 1,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "CAGR, %",
  },
  {
    id: 89,
    group: "S",
    category: "Wealth",
    indicator: "Debt to salary ratio",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "ratio",
  },
  {
    id: 90,
    group: "S",
    category: "Wealth",
    indicator: "Number of mobile phones per 1,000 population",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "per 1,000",
  },
  {
    id: 91,
    group: "S",
    category: "Wealth",
    indicator: "Decile income coefficient",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "ratio",
  },
  {
    id: 92,
    group: "S",
    category: "Wealth",
    indicator: "Decile income coefficient (change in last 3 years)",
    scope: 1,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "CAGR, %",
  },
  {
    id: 93,
    group: "S",
    category: "Wealth",
    indicator: "Poverty headcount ratio at national poverty lines",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "ratio",
  },
  {
    id: 94,
    group: "S",
    category: "Wealth",
    indicator:
      "Working poverty rate (percentage of employed living below US$1.90 PPP), 15+ age (%) ",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 95,
    group: "S",
    category: "Wealth",
    indicator: "Poverty headcount ratio at $2.15 PPP 2017 a day",
    scope: 0,
    dimension: "Current state",
    type: "Supportive",
    unit: "ratio",
  },
  {
    id: 96,
    group: "S",
    category: "Wealth",
    indicator: "Living spaces per capita, sq m (change in last 3 years)",
    scope: 0,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "CAGR, %",
  },
  {
    id: 97,
    group: "S",
    category: "Wealth",
    indicator: "Population living in slums (% of urban population)",
    scope: 0,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 98,
    group: "S",
    category: "Wealth",
    indicator: "Availability of finance (consumer loans)",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 99,
    group: "S",
    category: "Wealth",
    indicator: "Perception of wealth & poverty index",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "index",
  },
  {
    id: 100,
    group: "S",
    category: "Safety",
    indicator: "Road fatalities rate per 100,000 population",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "per 100,000",
  },
  {
    id: 101,
    group: "S",
    category: "Safety",
    indicator:
      "Road fatalities rate per 100,000 population (change in last 3 years)",
    scope: 1,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "CAGR, %",
  },
  {
    id: 102,
    group: "S",
    category: "Safety",
    indicator: "Violent crime rate per 100,000 population",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "per 100,000",
  },
  {
    id: 103,
    group: "S",
    category: "Safety",
    indicator:
      "Violent crime rate per 100,000 population (change in last 3 years)",
    scope: 0,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "CAGR, %",
  },
  {
    id: 104,
    group: "S",
    category: "Safety",
    indicator: "Crime rate per 100,000 population",
    scope: 0,
    dimension: "Current state",
    type: "Supportive",
    unit: "per 100,000",
  },
  {
    id: 105,
    group: "S",
    category: "Safety",
    indicator: "Crime rate per 100,000 population  (change in last 3 years)",
    scope: 0,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "CAGR, %",
  },
  {
    id: 106,
    group: "S",
    category: "Safety",
    indicator: "Police arrival speed",
    scope: 0,
    dimension: "Current state",
    type: "Supportive",
    unit: "min",
  },
  {
    id: 107,
    group: "S",
    category: "Safety",
    indicator: "Perception of safety index",
    scope: 0,
    dimension: "Current state",
    type: "Supportive",
    unit: "index",
  },
  {
    id: 108,
    group: "S",
    category: "Livability",
    indicator: "Number of LEED certified green buildings",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "certified square meters per capita",
  },
  {
    id: 109,
    group: "S",
    category: "Livability",
    indicator: "Number of CEEQUAL certified projects",
    scope: 2,
    dimension: "Current state",
    type: "Supportive",
    unit: "certified square meters per capita",
  },
  {
    id: 110,
    group: "S",
    category: "Livability",
    indicator: "Whether or not the city has ISO 37120 certification",
    scope: 2,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "Yes/No",
  },
  {
    id: 111,
    group: "S",
    category: "Livability",
    indicator: "Mobile connection coverage",
    scope: 0,
    dimension: "Current state",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 112,
    group: "S",
    category: "Livability",
    indicator: "Internet coverage",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 113,
    group: "S",
    category: "Livability",
    indicator: "Perception of livability index",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "index",
  },
  {
    id: 114,
    group: "S",
    category: "Livability",
    indicator: "Share of population in 1 km from hospitals",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "%",
  },
  {
    id: 115,
    group: "S",
    category: "Livability",
    indicator: "Share of population in 1 km from parks",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "%",
  },
  {
    id: 116,
    group: "S",
    category: "Transport",
    indicator: "Time loss in traffic",
    scope: 1,
    dimension: "Current state",
    type: "Key",
    unit: "%",
  },
  {
    id: 117,
    group: "S",
    category: "Transport",
    indicator: "Share of the population in 1 km from public transport stop",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 118,
    group: "S",
    category: "Transport",
    indicator:
      "Ratio of the cost of monthly public transport usage (the cheapest option) to average monthly income",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "ratio",
  },
  {
    id: 119,
    group: "S",
    category: "Transport",
    indicator:
      "Ratio of the cost of a 1-kilometer taxi ride to average monthly income",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "ratio",
  },
  {
    id: 120,
    group: "S",
    category: "Transport",
    indicator:
      "Percentage of city roads that are segregated and/or has specialized lane for cyclists",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 121,
    group: "S",
    category: "Transport",
    indicator:
      "Number of public electric vehicle (EV) charging points per 100,000 population",
    scope: 3,
    dimension: "Current state",
    type: "Supportive",
    unit: "per 100,000",
  },
  {
    id: 122,
    group: "S",
    category: "Transport",
    indicator: "Public transport (excluding subway) operates by schedule ",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "Yes/No",
  },
  {
    id: 123,
    group: "S",
    category: "Transport",
    indicator: "Perception of transport index",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "index",
  },
  {
    id: 124,
    group: "S",
    category: "Inclusion",
    indicator: "Female-friendly city",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "index",
  },
  {
    id: 125,
    group: "S",
    category: "Inclusion",
    indicator: "Number of refugees per 1,000 population",
    scope: 0,
    dimension: "Current state",
    type: "Supportive",
    unit: "per 1,000",
  },
  {
    id: 126,
    group: "S",
    category: "Inclusion",
    indicator: "Homeless people per 1,000 population",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "per 1,000",
  },
  {
    id: 127,
    group: "S",
    category: "Inclusion",
    indicator:
      "Difference in number of years of schooling between woman and man, woman to man ratio ",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "ratio",
  },
  {
    id: 128,
    group: "S",
    category: "Inclusion",
    indicator: "Slavery index",
    scope: 0,
    dimension: "Current state",
    type: "Supportive",
    unit: "index",
  },
  {
    id: 129,
    group: "S",
    category: "Inclusion",
    indicator:
      "Percentage of women aged 25-34 years old that have successfully completed secondary education",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "%",
  },
  {
    id: 130,
    group: "S",
    category: "Inclusion",
    indicator:
      "Regulations for building construction and equipment, public transport for people with disabilities",
    scope: 2,
    dimension: "Current state",
    type: "Supportive",
    unit: "Yes/No",
  },
  {
    id: 131,
    group: "S",
    category: "Inclusion",
    indicator: "Perception of inclusion index",
    scope: 0,
    dimension: "Current state",
    type: "Key",
    unit: "index",
  },
  {
    id: 132,
    group: "G",
    category: "Accountability",
    indicator: "City budget execution publication",
    scope: 1,
    dimension: "Current state",
    type: "Key",
    unit: "Yes/No",
  },
  {
    id: 133,
    group: "G",
    category: "Accountability",
    indicator: "City budget publication",
    scope: 1,
    dimension: "Current state",
    type: "Key",
    unit: "Yes/No",
  },
  {
    id: 134,
    group: "G",
    category: "Accountability",
    indicator: "Financial transparency on city government companies",
    scope: 2,
    dimension: "Current state",
    type: "Key",
    unit: "Yes/No",
  },
  {
    id: 135,
    group: "G",
    category: "Accountability",
    indicator: "ISO certification",
    scope: 2,
    dimension: "Current state",
    type: "Key",
    unit: "Yes/No",
  },
  {
    id: 136,
    group: "G",
    category: "Accountability",
    indicator: "City council checks and balances",
    scope: 1,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "Yes/No",
  },
  {
    id: 137,
    group: "G",
    category: "Accountability",
    indicator: "Plans to obtain ISO certification",
    scope: 2,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "Yes/No",
  },
  {
    id: 138,
    group: "G",
    category: "Accountability",
    indicator: "Perception of accountability index",
    scope: 1,
    dimension: "Current state",
    type: "Key",
    unit: "index",
  },
  {
    id: 139,
    group: "G",
    category: "City budget",
    indicator: "Poor financial condition",
    scope: 2,
    dimension: "Current state",
    type: "Key",
    unit: "Yes/No",
  },
  {
    id: 140,
    group: "G",
    category: "City budget",
    indicator:
      "Central/higher level government financial intervention taking place",
    scope: 2,
    dimension: "Current state",
    type: "Key",
    unit: "Yes/No",
  },
  {
    id: 141,
    group: "G",
    category: "City budget",
    indicator: "Long-term financial planning",
    scope: 3,
    dimension: "Ability & willingness",
    type: "Key",
    unit: "Yes/No",
  },
  {
    id: 142,
    group: "G",
    category: "City budget",
    indicator:
      "Central/higher level government financial intervention is considered",
    scope: 2,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "Yes/No",
  },
  {
    id: 143,
    group: "G",
    category: "City budget",
    indicator: "Prudent fiscal policy requirements",
    scope: 2,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "Yes/No",
  },
  {
    id: 144,
    group: "G",
    category: "City budget",
    indicator: "Medium-term planning",
    scope: 3,
    dimension: "Ability & willingness",
    type: "Key",
    unit: "Yes/No",
  },
  {
    id: 145,
    group: "G",
    category: "SME",
    indicator: "Number of SMEs per 100,000 population",
    scope: 2,
    dimension: "Current state",
    type: "Key",
    unit: "per 100,000",
  },
  {
    id: 146,
    group: "G",
    category: "SME",
    indicator: "Number of start-ups",
    scope: 2,
    dimension: "Current state",
    type: "Supportive",
    unit: "start-ups",
  },
  {
    id: 147,
    group: "G",
    category: "SME",
    indicator: "Global Startup Ecosystem Index",
    scope: 3,
    dimension: "Current state",
    type: "Supportive",
    unit: "index",
  },
  {
    id: 148,
    group: "G",
    category: "SME",
    indicator:
      "Number of SMEs per capita/100 000 population (change in last 3 years)",
    scope: 2,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "CAGR, %",
  },
  {
    id: 149,
    group: "G",
    category: "SME",
    indicator: "Number of start-ups (change in last 3 years)",
    scope: 2,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "CAGR, %",
  },
  {
    id: 150,
    group: "G",
    category: "Public services",
    indicator: "Free phone to call the police, ambulance, firefighters",
    scope: 0,
    dimension: "Current state",
    type: "Supportive",
    unit: "index",
  },
  {
    id: 151,
    group: "G",
    category: "Public services",
    indicator: "Services for working with citizens' appeals and complaint",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "Yes/No",
  },
  {
    id: 152,
    group: "G",
    category: "Public services",
    indicator: "E-gov services",
    scope: 1,
    dimension: "Current state",
    type: "Key",
    unit: "Yes/No",
  },
  {
    id: 153,
    group: "G",
    category: "Public services",
    indicator: "Perception of public services index: Public Services",
    scope: 1,
    dimension: "Current state",
    type: "Key",
    unit: "index",
  },
  {
    id: 154,
    group: "G",
    category: "Sustainability commitment",
    indicator: "City ESG reporting",
    scope: 3,
    dimension: "Ability & willingness",
    type: "Key",
    unit: "Yes/No",
  },
  {
    id: 155,
    group: "G",
    category: "Sustainability commitment",
    indicator: "City ESG reporting verification",
    scope: 3,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "Yes/No",
  },
  {
    id: 156,
    group: "G",
    category: "Sustainability commitment",
    indicator: "ESG planning",
    scope: 3,
    dimension: "Ability & willingness",
    type: "Key",
    unit: "Yes/No",
  },
  {
    id: 157,
    group: "G",
    category: "Sustainability commitment",
    indicator:
      "Plan with specific targets to develop and implement smart city principles",
    scope: 1,
    dimension: "Ability & willingness",
    type: "Supportive",
    unit: "Yes/No",
  },
  {
    id: 158,
    group: "G",
    category: "Sustainability commitment",
    indicator:
      "Rollout and status of ESG / UN SDG training across the municipal/asset workforce",
    scope: 1,
    dimension: "Current state",
    type: "Supportive",
    unit: "Yes/No",
  },
  {
    id: 159,
    group: "G",
    category: "Sustainability commitment",
    indicator:
      "City municipality involved in network or partnership promoting sustainable development (for example, C40 Cities network)",
    scope: 3,
    dimension: "Current state",
    type: "Supportive",
    unit: "Yes/No",
  },
];
