import { makeStyles } from "tss-react/mui";

export const useMainPageStyles = makeStyles()({
  root: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    backgroundImage: "url(/assets/mainPageBg.png)",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
  },
  title: {
    fontFamily: "SuisseIntl-Light",
    fontWeight: 400,
    fontSize: "6vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    color: "#fff",
    marginTop: "5vh",
  },
  content: {
    display: "flex",
    flexDirection: "row",
    width: "100%",
    color: "#fff",
    fontFamily: "SuisseIntl-Light",
    fontWeight: 400,
    fontSize: "4.5vh",
    marginTop: "15vh",
  },
  sectionWrapper: {
    flex: 1,
    paddingLeft: "15vh",
  },
  smallTextGroupWrapper: {
    display: "flex",
    flexDirection: "row",
    fontSize: "2vh",
    gap: "5vh",
    marginTop: "4vh",
  },
  smallTextWrapper: {
    alignSelf: "flex-start",
    display: "flex",
    flexDirection: "column",
    gap: "1vh",
    textWrap: "nowrap",
  },
  sectionTitle: {
    alignSelf: "flex-end",
  },
  whiteButton: {
    fontFamily: "SuisseIntl-Light",
    fontWeight: 600,
    backgroundColor: "#fff",
    color: "#000",
    width: "fit-content",
    padding: "1vh 3vh",
    borderRadius: "4vh",
    textTransform: "none",
    fontSize: "2.8vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "1vh",
    "&:hover": {
      backgroundColor: "#fff",
    },
  },
});
