import { makeStyles } from "tss-react/mui";

export const useNewsStyles = makeStyles()({
  contentWrapper: {
    position: "relative",
    overflowY: "scroll",
    margin: "0 10vh",
    height: "calc(100vh - 10.3vh)",
  },
  title: {
    fontFamily: "SuisseIntl-Light",
    fontWeight: 400,
    fontSize: "6.8vh",
    margin: "2vh 0vh 4vh",
  },
  titleBold: {
    fontFamily: "SuisseIntl-Regular",
    fontWeight: "700",
  },
  filtersAndProjectsWrapper: {
    display: "flex",
    flexDirection: "row",
    marginBottom: "10vh",
    gap: "2vh",
  },
  filtersWrapper: {
    // backgroundColor: "#F5F5F5",
    flex: 1,
  },
  projectsWrapper: {
    // backgroundColor: "red",
    flex: 4,
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    rowGap: "4vh",
    columnGap: "4vh",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    height: "fit-content",
  },
  addProjectBtn: {
    position: "sticky",
    zIndex: 1,
    top: "2vh",
    backgroundColor: "#000",
    color: "#fff",
    borderRadius: "50px",
    textTransform: "none",
    fontSize: "2.1vh",
    display: "flex",
    flexDirection: "row",
    gap: "1vh",
    padding: "1.5vh 3vh",
    textWrap: "nowrap",
  },
  filterGroupHeader: {
    fontFamily: "SuisseIntl-Light",
    fontWeight: 400,
    fontSize: "3.5vh",
    marginTop: "4vh",
    marginBottom: "1vh",
    textWrap: "nowrap",
  },
  filterList: {
    overflow: "visible",
    display: "flex",
    flexDirection: "column",
    gap: "0",
  },
  filterRow: {
    fontFamily: "SuisseIntl-Light",
    fontWeight: 400,
    fontSize: "2.1vh",
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginLeft: "-1vh",
    textWrap: "nowrap",
  },
  moreFiltersBtn: {
    fontFamily: "SuisseIntl-Light",
    fontWeight: 400,
    fontSize: "2.1vh",
    color: "#000",
    cursor: "pointer",
    marginTop: "1vh",
    opacity: "0.5",
  },
  projectItem: {
    position: "relative",
    overflow: "hidden",
    borderRadius: "3vh",
    backgroundColor: "#fff",
    width: "25vh",
    height: "45vh",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
    border: "1px solid #CCCCCC",
  },
  statItem: {
    fontFamily: "SuisseIntl-Light",
    fontWeight: 800,
    color: "#35CB00",
    border: "1px solid rgba(53, 203, 0, 0.5)",
    padding: "1vh 1.5vh",
    borderRadius: "50px",
    fontSize: "1.4vh",
    width: "fit-content",
  },
  projectImageWrapper: {
    width: "100%",
    height: "15vh",
    overflow: "hidden",
    backgroundSize: "cover",
    backgroundPosition: "center",
  },
  projectInfoWrapper: {
    display: "flex",
    flexDirection: "column",
    gap: "1vh",
    padding: "0 1.5vh",
    height: "20vh",
  },
  projectTitle: {
    cursor: "pointer",
    fontFamily: "SuisseIntl-Regular",
    fontWeight: 600,
    fontSize: "1.8vh",
  },
  projectSubTitle: {
    fontFamily: "SuisseIntl-Light",
    fontWeight: 400,
    fontSize: "1.5vh",
    opacity: "0.5",
  },
  projectStatsWrapper: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: "1.5vh",
  },
  impactLabel: {
    fontFamily: "SuisseIntl-Regular",
    fontWeight: 100,
    fontSize: "1.5vh",
  },
  likeBtn: {
    backgroundColor: "#2D67FF",
    fontSize: "1.5vh",
    color: "#fff",
    borderRadius: "50px",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    justifySelf: "flex-end",
    gap: "2vh",
    padding: ".7vh 1.5vh",
    textTransform: "none",
    width: "21vh",
    "&:hover": {
      backgroundColor: "#000",
    },
  },
  projectsOnMapBtn: {
    position: "absolute",
    top: "9vh",
    right: "6vw",
    zIndex: 200,
    cursor: "pointer",
    width: "12vh",
    height: "12vh",
  },
});
